// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "MeshUtils_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alphaWrap_cpp
Rcpp::List alphaWrap_cpp(const Rcpp::NumericMatrix pts, const double alphaRel, const double offsetRel);
RcppExport SEXP _MeshUtils_alphaWrap_cpp(SEXP ptsSEXP, SEXP alphaRelSEXP, SEXP offsetRelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const double >::type alphaRel(alphaRelSEXP);
    Rcpp::traits::input_parameter< const double >::type offsetRel(offsetRelSEXP);
    rcpp_result_gen = Rcpp::wrap(alphaWrap_cpp(pts, alphaRel, offsetRel));
    return rcpp_result_gen;
END_RCPP
}
// SurfMesh_cpp
Rcpp::List SurfMesh_cpp(const Rcpp::List rmeshIn, const bool clean, const bool triangulate, const bool normals);
RcppExport SEXP _MeshUtils_SurfMesh_cpp(SEXP rmeshInSEXP, SEXP cleanSEXP, SEXP triangulateSEXP, SEXP normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< const bool >::type clean(cleanSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(SurfMesh_cpp(rmeshIn, clean, triangulate, normals));
    return rcpp_result_gen;
END_RCPP
}
// doesBoundVolume_cpp
bool doesBoundVolume_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_doesBoundVolume_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(doesBoundVolume_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// doesSelfIntersect_cpp
bool doesSelfIntersect_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_doesSelfIntersect_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(doesSelfIntersect_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// isClosed_cpp
bool isClosed_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_isClosed_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(isClosed_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// orientToBoundVolume_cpp
Rcpp::List orientToBoundVolume_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_orientToBoundVolume_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(orientToBoundVolume_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// removeSelfIntersections_cpp
Rcpp::List removeSelfIntersections_cpp(const Rcpp::List rmeshIn, const unsigned int method);
RcppExport SEXP _MeshUtils_removeSelfIntersections_cpp(SEXP rmeshInSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(removeSelfIntersections_cpp(rmeshIn, method));
    return rcpp_result_gen;
END_RCPP
}
// getArea_cpp
double getArea_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_getArea_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getArea_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// getVolume_cpp
double getVolume_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_getVolume_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getVolume_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// getCentroid_cpp
Rcpp::NumericVector getCentroid_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_getCentroid_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(getCentroid_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// optimalBoundingBox_cpp
Rcpp::List optimalBoundingBox_cpp(const Rcpp::List rmeshIn);
RcppExport SEXP _MeshUtils_optimalBoundingBox_cpp(SEXP rmeshInSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    rcpp_result_gen = Rcpp::wrap(optimalBoundingBox_cpp(rmeshIn));
    return rcpp_result_gen;
END_RCPP
}
// boundingBox_cpp
Rcpp::List boundingBox_cpp(const Rcpp::List rmesh);
RcppExport SEXP _MeshUtils_boundingBox_cpp(SEXP rmeshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    rcpp_result_gen = Rcpp::wrap(boundingBox_cpp(rmesh));
    return rcpp_result_gen;
END_RCPP
}
// getDistance_cpp
Rcpp::NumericVector getDistance_cpp(const Rcpp::List rmesh, const Rcpp::NumericMatrix points);
RcppExport SEXP _MeshUtils_getDistance_cpp(SEXP rmeshSEXP, SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh(rmeshSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(getDistance_cpp(rmesh, points));
    return rcpp_result_gen;
END_RCPP
}
// getHausdorffApprox_cpp
double getHausdorffApprox_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, bool symmetric);
RcppExport SEXP _MeshUtils_getHausdorffApprox_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(getHausdorffApprox_cpp(rmesh1, rmesh2, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// getHausdorffEst_cpp
double getHausdorffEst_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, bool symmetric, double errorBound);
RcppExport SEXP _MeshUtils_getHausdorffEst_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP symmetricSEXP, SEXP errorBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< double >::type errorBound(errorBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(getHausdorffEst_cpp(rmesh1, rmesh2, symmetric, errorBound));
    return rcpp_result_gen;
END_RCPP
}
// remeshIsotropic_cpp
Rcpp::List remeshIsotropic_cpp(const Rcpp::List rmeshIn, const double targetEdgeLen, const unsigned nIter, const unsigned nRelaxSteps);
RcppExport SEXP _MeshUtils_remeshIsotropic_cpp(SEXP rmeshInSEXP, SEXP targetEdgeLenSEXP, SEXP nIterSEXP, SEXP nRelaxStepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< const double >::type targetEdgeLen(targetEdgeLenSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type nRelaxSteps(nRelaxStepsSEXP);
    rcpp_result_gen = Rcpp::wrap(remeshIsotropic_cpp(rmeshIn, targetEdgeLen, nIter, nRelaxSteps));
    return rcpp_result_gen;
END_RCPP
}
// subdivideCatmullClark_cpp
Rcpp::List subdivideCatmullClark_cpp(const Rcpp::List rmeshIn, unsigned int nIter);
RcppExport SEXP _MeshUtils_subdivideCatmullClark_cpp(SEXP rmeshInSEXP, SEXP nIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nIter(nIterSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideCatmullClark_cpp(rmeshIn, nIter));
    return rcpp_result_gen;
END_RCPP
}
// subdivideDooSabin_cpp
Rcpp::List subdivideDooSabin_cpp(const Rcpp::List rmeshIn, unsigned int nIter);
RcppExport SEXP _MeshUtils_subdivideDooSabin_cpp(SEXP rmeshInSEXP, SEXP nIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nIter(nIterSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideDooSabin_cpp(rmeshIn, nIter));
    return rcpp_result_gen;
END_RCPP
}
// subdivideSqrt3_cpp
Rcpp::List subdivideSqrt3_cpp(const Rcpp::List rmeshIn, unsigned int nIter);
RcppExport SEXP _MeshUtils_subdivideSqrt3_cpp(SEXP rmeshInSEXP, SEXP nIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshIn(rmeshInSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nIter(nIterSEXP);
    rcpp_result_gen = Rcpp::wrap(subdivideSqrt3_cpp(rmeshIn, nIter));
    return rcpp_result_gen;
END_RCPP
}
// jet_normals_cpp
Rcpp::NumericMatrix jet_normals_cpp(const Rcpp::NumericMatrix pts, const unsigned nbNeighbors);
RcppExport SEXP _MeshUtils_jet_normals_cpp(SEXP ptsSEXP, SEXP nbNeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type nbNeighbors(nbNeighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(jet_normals_cpp(pts, nbNeighbors));
    return rcpp_result_gen;
END_RCPP
}
// pca_normals_cpp
Rcpp::NumericMatrix pca_normals_cpp(Rcpp::NumericMatrix pts, unsigned nbNeighbors);
RcppExport SEXP _MeshUtils_pca_normals_cpp(SEXP ptsSEXP, SEXP nbNeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type nbNeighbors(nbNeighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_normals_cpp(pts, nbNeighbors));
    return rcpp_result_gen;
END_RCPP
}
// intersectionEK_cpp
Rcpp::List intersectionEK_cpp(const Rcpp::List rmeshes, const bool clean, const bool normals, const Rcpp::LogicalVector triangulate);
RcppExport SEXP _MeshUtils_intersectionEK_cpp(SEXP rmeshesSEXP, SEXP cleanSEXP, SEXP normalsSEXP, SEXP triangulateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshes(rmeshesSEXP);
    Rcpp::traits::input_parameter< const bool >::type clean(cleanSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector >::type triangulate(triangulateSEXP);
    rcpp_result_gen = Rcpp::wrap(intersectionEK_cpp(rmeshes, clean, normals, triangulate));
    return rcpp_result_gen;
END_RCPP
}
// differenceEK_cpp
Rcpp::List differenceEK_cpp(const Rcpp::List rmesh1, const Rcpp::List rmesh2, const bool clean, const bool normals, const bool triangulate1, const bool triangulate2);
RcppExport SEXP _MeshUtils_differenceEK_cpp(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP cleanSEXP, SEXP normalsSEXP, SEXP triangulate1SEXP, SEXP triangulate2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< const bool >::type clean(cleanSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate1(triangulate1SEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate2(triangulate2SEXP);
    rcpp_result_gen = Rcpp::wrap(differenceEK_cpp(rmesh1, rmesh2, clean, normals, triangulate1, triangulate2));
    return rcpp_result_gen;
END_RCPP
}
// unionEK_cpp
Rcpp::List unionEK_cpp(const Rcpp::List rmeshes, const bool clean, const bool normals, const Rcpp::LogicalVector triangulate);
RcppExport SEXP _MeshUtils_unionEK_cpp(SEXP rmeshesSEXP, SEXP cleanSEXP, SEXP normalsSEXP, SEXP triangulateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmeshes(rmeshesSEXP);
    Rcpp::traits::input_parameter< const bool >::type clean(cleanSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector >::type triangulate(triangulateSEXP);
    rcpp_result_gen = Rcpp::wrap(unionEK_cpp(rmeshes, clean, normals, triangulate));
    return rcpp_result_gen;
END_RCPP
}
// readFile_cpp
Rcpp::List readFile_cpp(const std::string filename);
RcppExport SEXP _MeshUtils_readFile_cpp(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(readFile_cpp(filename));
    return rcpp_result_gen;
END_RCPP
}
// writeFile_cpp
void writeFile_cpp(const std::string filename, const bool binary, const int precision, const Rcpp::NumericMatrix vertices, const Rcpp::List faceList);
RcppExport SEXP _MeshUtils_writeFile_cpp(SEXP filenameSEXP, SEXP binarySEXP, SEXP precisionSEXP, SEXP verticesSEXP, SEXP faceListSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< const int >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type faceList(faceListSEXP);
    writeFile_cpp(filename, binary, precision, vertices, faceList);
    return R_NilValue;
END_RCPP
}
// reconstructAFS_cpp
Rcpp::List reconstructAFS_cpp(const Rcpp::NumericMatrix pts, const unsigned nNeighs, const bool clean);
RcppExport SEXP _MeshUtils_reconstructAFS_cpp(SEXP ptsSEXP, SEXP nNeighsSEXP, SEXP cleanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type nNeighs(nNeighsSEXP);
    Rcpp::traits::input_parameter< const bool >::type clean(cleanSEXP);
    rcpp_result_gen = Rcpp::wrap(reconstructAFS_cpp(pts, nNeighs, clean));
    return rcpp_result_gen;
END_RCPP
}
// reconstructPoisson_cpp
Rcpp::List reconstructPoisson_cpp(const Rcpp::NumericMatrix pts, const Rcpp::NumericMatrix normals, const double spacing, const double smAngle, const double smRadius, const double smDistance, const bool clean);
RcppExport SEXP _MeshUtils_reconstructPoisson_cpp(SEXP ptsSEXP, SEXP normalsSEXP, SEXP spacingSEXP, SEXP smAngleSEXP, SEXP smRadiusSEXP, SEXP smDistanceSEXP, SEXP cleanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const double >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< const double >::type smAngle(smAngleSEXP);
    Rcpp::traits::input_parameter< const double >::type smRadius(smRadiusSEXP);
    Rcpp::traits::input_parameter< const double >::type smDistance(smDistanceSEXP);
    Rcpp::traits::input_parameter< const bool >::type clean(cleanSEXP);
    rcpp_result_gen = Rcpp::wrap(reconstructPoisson_cpp(pts, normals, spacing, smAngle, smRadius, smDistance, clean));
    return rcpp_result_gen;
END_RCPP
}
// reconstructSSS_cpp
Rcpp::List reconstructSSS_cpp(const Rcpp::NumericMatrix pts, const size_t scaleIterations, const unsigned nNeighs, const unsigned nSamples, const bool separateShells, const bool forceManifold, const double borderAngle);
RcppExport SEXP _MeshUtils_reconstructSSS_cpp(SEXP ptsSEXP, SEXP scaleIterationsSEXP, SEXP nNeighsSEXP, SEXP nSamplesSEXP, SEXP separateShellsSEXP, SEXP forceManifoldSEXP, SEXP borderAngleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const size_t >::type scaleIterations(scaleIterationsSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type nNeighs(nNeighsSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type nSamples(nSamplesSEXP);
    Rcpp::traits::input_parameter< const bool >::type separateShells(separateShellsSEXP);
    Rcpp::traits::input_parameter< const bool >::type forceManifold(forceManifoldSEXP);
    Rcpp::traits::input_parameter< const double >::type borderAngle(borderAngleSEXP);
    rcpp_result_gen = Rcpp::wrap(reconstructSSS_cpp(pts, scaleIterations, nNeighs, nSamples, separateShells, forceManifold, borderAngle));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MeshUtils_alphaWrap_cpp", (DL_FUNC) &_MeshUtils_alphaWrap_cpp, 3},
    {"_MeshUtils_SurfMesh_cpp", (DL_FUNC) &_MeshUtils_SurfMesh_cpp, 4},
    {"_MeshUtils_doesBoundVolume_cpp", (DL_FUNC) &_MeshUtils_doesBoundVolume_cpp, 1},
    {"_MeshUtils_doesSelfIntersect_cpp", (DL_FUNC) &_MeshUtils_doesSelfIntersect_cpp, 1},
    {"_MeshUtils_isClosed_cpp", (DL_FUNC) &_MeshUtils_isClosed_cpp, 1},
    {"_MeshUtils_orientToBoundVolume_cpp", (DL_FUNC) &_MeshUtils_orientToBoundVolume_cpp, 1},
    {"_MeshUtils_removeSelfIntersections_cpp", (DL_FUNC) &_MeshUtils_removeSelfIntersections_cpp, 2},
    {"_MeshUtils_getArea_cpp", (DL_FUNC) &_MeshUtils_getArea_cpp, 1},
    {"_MeshUtils_getVolume_cpp", (DL_FUNC) &_MeshUtils_getVolume_cpp, 1},
    {"_MeshUtils_getCentroid_cpp", (DL_FUNC) &_MeshUtils_getCentroid_cpp, 1},
    {"_MeshUtils_optimalBoundingBox_cpp", (DL_FUNC) &_MeshUtils_optimalBoundingBox_cpp, 1},
    {"_MeshUtils_boundingBox_cpp", (DL_FUNC) &_MeshUtils_boundingBox_cpp, 1},
    {"_MeshUtils_getDistance_cpp", (DL_FUNC) &_MeshUtils_getDistance_cpp, 2},
    {"_MeshUtils_getHausdorffApprox_cpp", (DL_FUNC) &_MeshUtils_getHausdorffApprox_cpp, 3},
    {"_MeshUtils_getHausdorffEst_cpp", (DL_FUNC) &_MeshUtils_getHausdorffEst_cpp, 4},
    {"_MeshUtils_remeshIsotropic_cpp", (DL_FUNC) &_MeshUtils_remeshIsotropic_cpp, 4},
    {"_MeshUtils_subdivideCatmullClark_cpp", (DL_FUNC) &_MeshUtils_subdivideCatmullClark_cpp, 2},
    {"_MeshUtils_subdivideDooSabin_cpp", (DL_FUNC) &_MeshUtils_subdivideDooSabin_cpp, 2},
    {"_MeshUtils_subdivideSqrt3_cpp", (DL_FUNC) &_MeshUtils_subdivideSqrt3_cpp, 2},
    {"_MeshUtils_jet_normals_cpp", (DL_FUNC) &_MeshUtils_jet_normals_cpp, 2},
    {"_MeshUtils_pca_normals_cpp", (DL_FUNC) &_MeshUtils_pca_normals_cpp, 2},
    {"_MeshUtils_intersectionEK_cpp", (DL_FUNC) &_MeshUtils_intersectionEK_cpp, 4},
    {"_MeshUtils_differenceEK_cpp", (DL_FUNC) &_MeshUtils_differenceEK_cpp, 6},
    {"_MeshUtils_unionEK_cpp", (DL_FUNC) &_MeshUtils_unionEK_cpp, 4},
    {"_MeshUtils_readFile_cpp", (DL_FUNC) &_MeshUtils_readFile_cpp, 1},
    {"_MeshUtils_writeFile_cpp", (DL_FUNC) &_MeshUtils_writeFile_cpp, 5},
    {"_MeshUtils_reconstructAFS_cpp", (DL_FUNC) &_MeshUtils_reconstructAFS_cpp, 3},
    {"_MeshUtils_reconstructPoisson_cpp", (DL_FUNC) &_MeshUtils_reconstructPoisson_cpp, 7},
    {"_MeshUtils_reconstructSSS_cpp", (DL_FUNC) &_MeshUtils_reconstructSSS_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MeshUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
