# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphaWrap_cpp <- function(pts, alphaRel, offsetRel) {
    .Call(`_MeshUtils_alphaWrap_cpp`, pts, alphaRel, offsetRel)
}

intersectionEK_cpp <- function(rmeshes, triangulate, repairSoup, normals) {
    .Call(`_MeshUtils_intersectionEK_cpp`, rmeshes, triangulate, repairSoup, normals)
}

differenceEK_cpp <- function(rmesh1, rmesh2, triangulate1, triangulate2, repairSoup, normals) {
    .Call(`_MeshUtils_differenceEK_cpp`, rmesh1, rmesh2, triangulate1, triangulate2, repairSoup, normals)
}

unionEK_cpp <- function(rmeshes, triangulate, repairSoup, normals) {
    .Call(`_MeshUtils_unionEK_cpp`, rmeshes, triangulate, repairSoup, normals)
}

makeMesh_cpp <- function(rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals) {
    .Call(`_MeshUtils_makeMesh_cpp`, rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals)
}

isValid_cpp <- function(rmesh) {
    .Call(`_MeshUtils_isValid_cpp`, rmesh)
}

hasGarbage_cpp <- function(rmesh) {
    .Call(`_MeshUtils_hasGarbage_cpp`, rmesh)
}

doesBoundVolume_cpp <- function(rmesh, triangulate = FALSE) {
    .Call(`_MeshUtils_doesBoundVolume_cpp`, rmesh, triangulate)
}

doesSelfIntersect_cpp <- function(rmesh, triangulate = FALSE) {
    .Call(`_MeshUtils_doesSelfIntersect_cpp`, rmesh, triangulate)
}

isClosed_cpp <- function(rmesh) {
    .Call(`_MeshUtils_isClosed_cpp`, rmesh)
}

orientToBoundVolume_cpp <- function(rmesh, triangulate = FALSE) {
    .Call(`_MeshUtils_orientToBoundVolume_cpp`, rmesh, triangulate)
}

removeSelfIntersections_cpp <- function(rmesh, triangulate, method) {
    .Call(`_MeshUtils_removeSelfIntersections_cpp`, rmesh, triangulate, method)
}

fillBoundaryHoles_cpp <- function(rmesh, fairHole, maxNumHoles) {
    .Call(`_MeshUtils_fillBoundaryHoles_cpp`, rmesh, fairHole, maxNumHoles)
}

getArea_cpp <- function(rmesh, triangulate = FALSE) {
    .Call(`_MeshUtils_getArea_cpp`, rmesh, triangulate)
}

getVolume_cpp <- function(rmesh, triangulate = FALSE) {
    .Call(`_MeshUtils_getVolume_cpp`, rmesh, triangulate)
}

getCentroid_cpp <- function(rmesh, triangulate = FALSE) {
    .Call(`_MeshUtils_getCentroid_cpp`, rmesh, triangulate)
}

optimalBoundingBox_cpp <- function(rmeshIn) {
    .Call(`_MeshUtils_optimalBoundingBox_cpp`, rmeshIn)
}

boundingBox_cpp <- function(rmesh) {
    .Call(`_MeshUtils_boundingBox_cpp`, rmesh)
}

getDistance_cpp <- function(rmesh, points, triangulate = FALSE) {
    .Call(`_MeshUtils_getDistance_cpp`, rmesh, points, triangulate)
}

getHausdorffApprox_cpp <- function(rmesh1, rmesh2, symmetric, triangulate1 = FALSE, triangulate2 = FALSE) {
    .Call(`_MeshUtils_getHausdorffApprox_cpp`, rmesh1, rmesh2, symmetric, triangulate1, triangulate2)
}

getHausdorffEst_cpp <- function(rmesh1, rmesh2, symmetric, errorBound, triangulate1 = FALSE, triangulate2 = FALSE) {
    .Call(`_MeshUtils_getHausdorffEst_cpp`, rmesh1, rmesh2, symmetric, errorBound, triangulate1, triangulate2)
}

remeshIsotropicUniform_cpp <- function(rmesh, targetEdgeLen, nIter, nRelaxSteps) {
    .Call(`_MeshUtils_remeshIsotropicUniform_cpp`, rmesh, targetEdgeLen, nIter, nRelaxSteps)
}

remeshIsotropicAdapt_cpp <- function(rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps) {
    .Call(`_MeshUtils_remeshIsotropicAdapt_cpp`, rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps)
}

subdivideCatmullClark_cpp <- function(rmesh, nIter, triangulate) {
    .Call(`_MeshUtils_subdivideCatmullClark_cpp`, rmesh, nIter, triangulate)
}

subdivideDooSabin_cpp <- function(rmesh, nIter, triangulate) {
    .Call(`_MeshUtils_subdivideDooSabin_cpp`, rmesh, nIter, triangulate)
}

subdivideSqrt3_cpp <- function(rmesh, nIter, triangulate) {
    .Call(`_MeshUtils_subdivideSqrt3_cpp`, rmesh, nIter, triangulate)
}

jet_normals_cpp <- function(pts, nbNeighbors) {
    .Call(`_MeshUtils_jet_normals_cpp`, pts, nbNeighbors)
}

pca_normals_cpp <- function(pts, nbNeighbors) {
    .Call(`_MeshUtils_pca_normals_cpp`, pts, nbNeighbors)
}

readFileSoup_cpp <- function(filename) {
    .Call(`_MeshUtils_readFileSoup_cpp`, filename)
}

readFileMesh_cpp <- function(filename, binary) {
    .Call(`_MeshUtils_readFileMesh_cpp`, filename, binary)
}

writeFile_cpp <- function(filename, binary, precision, vertices, faceList) {
    invisible(.Call(`_MeshUtils_writeFile_cpp`, filename, binary, precision, vertices, faceList))
}

reconstructAFS_cpp <- function(pts, nNeighbors, repairSoup) {
    .Call(`_MeshUtils_reconstructAFS_cpp`, pts, nNeighbors, repairSoup)
}

reconstructPoisson_cpp <- function(pts, normals, spacing, smAngle, smRadius, smDistance) {
    .Call(`_MeshUtils_reconstructPoisson_cpp`, pts, normals, spacing, smAngle, smRadius, smDistance)
}

reconstructSSS_cpp <- function(pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup) {
    .Call(`_MeshUtils_reconstructSSS_cpp`, pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup)
}

