# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphaWrap_cpp <- function(pts, alphaRel, offsetRel) {
    .Call(`_MeshUtils_alphaWrap_cpp`, pts, alphaRel, offsetRel)
}

SurfMesh_cpp <- function(rmeshIn, clean, triangulate, normals) {
    .Call(`_MeshUtils_SurfMesh_cpp`, rmeshIn, clean, triangulate, normals)
}

doesBoundVolume_cpp <- function(rmesh) {
    .Call(`_MeshUtils_doesBoundVolume_cpp`, rmesh)
}

doesSelfIntersect_cpp <- function(rmesh) {
    .Call(`_MeshUtils_doesSelfIntersect_cpp`, rmesh)
}

isClosed_cpp <- function(rmesh) {
    .Call(`_MeshUtils_isClosed_cpp`, rmesh)
}

orientToBoundVolume_cpp <- function(rmesh) {
    .Call(`_MeshUtils_orientToBoundVolume_cpp`, rmesh)
}

removeSelfIntersections_cpp <- function(rmeshIn, method) {
    .Call(`_MeshUtils_removeSelfIntersections_cpp`, rmeshIn, method)
}

getArea_cpp <- function(rmesh) {
    .Call(`_MeshUtils_getArea_cpp`, rmesh)
}

getVolume_cpp <- function(rmesh) {
    .Call(`_MeshUtils_getVolume_cpp`, rmesh)
}

getCentroid_cpp <- function(rmesh) {
    .Call(`_MeshUtils_getCentroid_cpp`, rmesh)
}

optimalBoundingBox_cpp <- function(rmeshIn) {
    .Call(`_MeshUtils_optimalBoundingBox_cpp`, rmeshIn)
}

boundingBox_cpp <- function(rmesh) {
    .Call(`_MeshUtils_boundingBox_cpp`, rmesh)
}

getDistance_cpp <- function(rmesh, points) {
    .Call(`_MeshUtils_getDistance_cpp`, rmesh, points)
}

getHausdorffApprox_cpp <- function(rmesh1, rmesh2, symmetric) {
    .Call(`_MeshUtils_getHausdorffApprox_cpp`, rmesh1, rmesh2, symmetric)
}

getHausdorffEst_cpp <- function(rmesh1, rmesh2, symmetric, errorBound) {
    .Call(`_MeshUtils_getHausdorffEst_cpp`, rmesh1, rmesh2, symmetric, errorBound)
}

remeshIsotropic_cpp <- function(rmeshIn, targetEdgeLen, nIter, nRelaxSteps) {
    .Call(`_MeshUtils_remeshIsotropic_cpp`, rmeshIn, targetEdgeLen, nIter, nRelaxSteps)
}

subdivideCatmullClark_cpp <- function(rmeshIn, nIter) {
    .Call(`_MeshUtils_subdivideCatmullClark_cpp`, rmeshIn, nIter)
}

subdivideDooSabin_cpp <- function(rmeshIn, nIter) {
    .Call(`_MeshUtils_subdivideDooSabin_cpp`, rmeshIn, nIter)
}

subdivideSqrt3_cpp <- function(rmeshIn, nIter) {
    .Call(`_MeshUtils_subdivideSqrt3_cpp`, rmeshIn, nIter)
}

jet_normals_cpp <- function(pts, nbNeighbors) {
    .Call(`_MeshUtils_jet_normals_cpp`, pts, nbNeighbors)
}

pca_normals_cpp <- function(pts, nbNeighbors) {
    .Call(`_MeshUtils_pca_normals_cpp`, pts, nbNeighbors)
}

intersectionEK_cpp <- function(rmeshes, clean, normals, triangulate) {
    .Call(`_MeshUtils_intersectionEK_cpp`, rmeshes, clean, normals, triangulate)
}

differenceEK_cpp <- function(rmesh1, rmesh2, clean, normals, triangulate1, triangulate2) {
    .Call(`_MeshUtils_differenceEK_cpp`, rmesh1, rmesh2, clean, normals, triangulate1, triangulate2)
}

unionEK_cpp <- function(rmeshes, clean, normals, triangulate) {
    .Call(`_MeshUtils_unionEK_cpp`, rmeshes, clean, normals, triangulate)
}

readFile_cpp <- function(filename) {
    .Call(`_MeshUtils_readFile_cpp`, filename)
}

writeFile_cpp <- function(filename, binary, precision, vertices, faceList) {
    invisible(.Call(`_MeshUtils_writeFile_cpp`, filename, binary, precision, vertices, faceList))
}

reconstructAFS_cpp <- function(pts, nNeighs, clean) {
    .Call(`_MeshUtils_reconstructAFS_cpp`, pts, nNeighs, clean)
}

reconstructPoisson_cpp <- function(pts, normals, spacing, smAngle, smRadius, smDistance, clean) {
    .Call(`_MeshUtils_reconstructPoisson_cpp`, pts, normals, spacing, smAngle, smRadius, smDistance, clean)
}

reconstructSSS_cpp <- function(pts, scaleIterations, nNeighs, nSamples, separateShells, forceManifold, borderAngle) {
    .Call(`_MeshUtils_reconstructSSS_cpp`, pts, scaleIterations, nNeighs, nSamples, separateShells, forceManifold, borderAngle)
}

