# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphaWrapPoints_cpp <- function(pts, alpha_rel, offset_rel, normals) {
    .Call(`_MeshUtils_alphaWrapPoints_cpp`, pts, alpha_rel, offset_rel, normals)
}

alphaWrapMesh_cpp <- function(rmesh, alpha_rel, offset_rel, normals) {
    .Call(`_MeshUtils_alphaWrapMesh_cpp`, rmesh, alpha_rel, offset_rel, normals)
}

boolIntersectionEK_cpp <- function(rmeshes, repairSoup, normals) {
    .Call(`_MeshUtils_boolIntersectionEK_cpp`, rmeshes, repairSoup, normals)
}

boolDifferenceEK_cpp <- function(rmesh1, rmesh2, repairSoup, normals) {
    .Call(`_MeshUtils_boolDifferenceEK_cpp`, rmesh1, rmesh2, repairSoup, normals)
}

boolUnionEK_cpp <- function(rmeshes, repairSoup, normals) {
    .Call(`_MeshUtils_boolUnionEK_cpp`, rmeshes, repairSoup, normals)
}

getHausdorffApprox_cpp <- function(rmesh1, rmesh2, symmetric) {
    .Call(`_MeshUtils_getHausdorffApprox_cpp`, rmesh1, rmesh2, symmetric)
}

getHausdorffEst_cpp <- function(rmesh1, rmesh2, symmetric, error_bound) {
    .Call(`_MeshUtils_getHausdorffEst_cpp`, rmesh1, rmesh2, symmetric, error_bound)
}

makeMesh_cpp <- function(rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals) {
    .Call(`_MeshUtils_makeMesh_cpp`, rmesh, triangulate, repairSoup, removeIntersections, removeMethod, fillHoles, fairHole, maxNumHoles, normals)
}

isValid_cpp <- function(rmesh) {
    .Call(`_MeshUtils_isValid_cpp`, rmesh)
}

hasGarbage_cpp <- function(rmesh) {
    .Call(`_MeshUtils_hasGarbage_cpp`, rmesh)
}

doesBoundVolume_cpp <- function(rmesh) {
    .Call(`_MeshUtils_doesBoundVolume_cpp`, rmesh)
}

doesSelfIntersect_cpp <- function(rmesh) {
    .Call(`_MeshUtils_doesSelfIntersect_cpp`, rmesh)
}

isClosed_cpp <- function(rmesh) {
    .Call(`_MeshUtils_isClosed_cpp`, rmesh)
}

orientToBoundVolume_cpp <- function(rmesh, normals) {
    .Call(`_MeshUtils_orientToBoundVolume_cpp`, rmesh, normals)
}

removeSelfIntersections_cpp <- function(rmesh, method, normals) {
    .Call(`_MeshUtils_removeSelfIntersections_cpp`, rmesh, method, normals)
}

fillBoundaryHoles_cpp <- function(rmesh, fairHole, maxNumHoles, normals) {
    .Call(`_MeshUtils_fillBoundaryHoles_cpp`, rmesh, fairHole, maxNumHoles, normals)
}

getArea_cpp <- function(rmesh) {
    .Call(`_MeshUtils_getArea_cpp`, rmesh)
}

getVolume_cpp <- function(rmesh) {
    .Call(`_MeshUtils_getVolume_cpp`, rmesh)
}

getCentroid_cpp <- function(rmesh) {
    .Call(`_MeshUtils_getCentroid_cpp`, rmesh)
}

optimalBoundingBox_cpp <- function(rmeshIn, triangulate, normals) {
    .Call(`_MeshUtils_optimalBoundingBox_cpp`, rmeshIn, triangulate, normals)
}

boundingBox_cpp <- function(rmesh) {
    .Call(`_MeshUtils_boundingBox_cpp`, rmesh)
}

getDistance_cpp <- function(rmesh, points) {
    .Call(`_MeshUtils_getDistance_cpp`, rmesh, points)
}

addVNormals_cpp <- function(rmesh) {
    .Call(`_MeshUtils_addVNormals_cpp`, rmesh)
}

triangulateMesh_cpp <- function(rmesh, normals) {
    .Call(`_MeshUtils_triangulateMesh_cpp`, rmesh, normals)
}

jet_pca_normals_cpp <- function(pts, nbNeighbors, method) {
    .Call(`_MeshUtils_jet_pca_normals_cpp`, pts, nbNeighbors, method)
}

readFileSoup_cpp <- function(filename, binary) {
    .Call(`_MeshUtils_readFileSoup_cpp`, filename, binary)
}

readFileMesh_cpp <- function(filename, binary, normals) {
    .Call(`_MeshUtils_readFileMesh_cpp`, filename, binary, normals)
}

writeFile_cpp <- function(filename, binary, precision, vertices, faceList) {
    invisible(.Call(`_MeshUtils_writeFile_cpp`, filename, binary, precision, vertices, faceList))
}

reconstructAFS_cpp <- function(pts, nNeighbors, repairSoup, normals) {
    .Call(`_MeshUtils_reconstructAFS_cpp`, pts, nNeighbors, repairSoup, normals)
}

reconstructPoisson_cpp <- function(pts, normalsIn, spacing, smAngle, smRadius, smDistance, normals) {
    .Call(`_MeshUtils_reconstructPoisson_cpp`, pts, normalsIn, spacing, smAngle, smRadius, smDistance, normals)
}

reconstructSSS_cpp <- function(pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup, normals) {
    .Call(`_MeshUtils_reconstructSSS_cpp`, pts, scaleIterations, nNeighbors, nSamples, separateShells, forceManifold, borderAngle, repairSoup, normals)
}

remeshIsotropicUniform_cpp <- function(rmesh, targetEdgeLen, nIter, nRelaxSteps, normals) {
    .Call(`_MeshUtils_remeshIsotropicUniform_cpp`, rmesh, targetEdgeLen, nIter, nRelaxSteps, normals)
}

remeshIsotropicAdapt_cpp <- function(rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps, normals) {
    .Call(`_MeshUtils_remeshIsotropicAdapt_cpp`, rmesh, tol, edgeMin, edgeMax, nIter, nRelaxSteps, normals)
}

smoothShape_cpp <- function(rmesh, indices, nIter, time, normals) {
    .Call(`_MeshUtils_smoothShape_cpp`, rmesh, indices, nIter, time, normals)
}

subdivideCatmullClark_cpp <- function(rmesh, nIter, normals) {
    .Call(`_MeshUtils_subdivideCatmullClark_cpp`, rmesh, nIter, normals)
}

subdivideDooSabin_cpp <- function(rmesh, nIter, triangulate, normals) {
    .Call(`_MeshUtils_subdivideDooSabin_cpp`, rmesh, nIter, triangulate, normals)
}

subdivideSqrt3_cpp <- function(rmesh, nIter, normals) {
    .Call(`_MeshUtils_subdivideSqrt3_cpp`, rmesh, nIter, normals)
}

subdivideLoop_cpp <- function(rmesh, nIter, normals) {
    .Call(`_MeshUtils_subdivideLoop_cpp`, rmesh, nIter, normals)
}

